[package]
name = "PLottery"
type = "contract"
authors = ["nodestarQ"]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.8", directory="noir-projects/aztec-nr/aztec" }
authwit={ git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.8", directory="noir-projects/aztec-nr/authwit"}
compressed_string = {git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.8", directory="noir-projects/aztec-nr/compressed-string"}
value_note = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.8", directory="noir-projects/aztec-nr/value-note"}
easy_private_state = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.87.8", directory="noir-projects/aztec-nr/easy-private-state"}
poseidon = { git = "https://github.com/noir-lang/poseidon", tag = "v0.1.0" }

